export const BOT_ROWS = [
  {
    id: 'jmfx',
    name: 'JM FX (Gold)',
    symbol: 'XAUUSD',
    type: 'Session scalp + ML',
    spread: 'Higher',
    session: 'PH schedule (7AM–8:30PM EMA, evening SMC)',
    blowUp: 'Low–medium',
    martingale: 'No',
    verdict: 'Production desk — do not modify from Lab',
    highlight: true,
  },
  {
    id: 'scalper',
    name: 'Generic Scalper EA',
    symbol: 'EUR/USD, USD/JPY',
    type: 'Tick / M1–M5 scalp',
    spread: 'Very low (best on ECN)',
    session: 'London / NY overlap',
    blowUp: 'Medium',
    martingale: 'Rare',
    verdict: 'Good for tight-spread majors',
    highlight: false,
  },
  {
    id: 'grid',
    name: 'Grid / Martingale EA',
    symbol: 'AUD/NZD, EUR/CHF',
    type: 'Range / mean reversion',
    spread: 'Medium',
    session: 'Quiet hours (Asian)',
    blowUp: 'Very high',
    martingale: 'Often yes',
    verdict: 'High blow-up risk — lab only with demo',
    highlight: false,
  },
  {
    id: 'trend',
    name: 'Trend / Breakout EA',
    symbol: 'GBP/USD, XAUUSD',
    type: 'Trend follow / breakout',
    spread: 'Medium',
    session: 'London open, NY',
    blowUp: 'Medium',
    martingale: 'No',
    verdict: 'Overlaps with SMC/VWAP ideas on gold',
    highlight: false,
  },
]

export const PAIR_EXPERIMENTS = [
  {
    id: 'EURUSD',
    label: 'EUR/USD',
    note: 'Tight spread · good scalper sandbox candidate',
    status: 'planned',
  },
  {
    id: 'GBPUSD',
    label: 'GBP/USD',
    note: 'Higher volatility · trend/breakout experiments',
    status: 'planned',
  },
  {
    id: 'AUDNZD',
    label: 'AUD/NZD',
    note: 'Mean-reverting · grid research only (demo)',
    status: 'planned',
  },
  {
    id: 'XAUUSD',
    label: 'XAUUSD (reference)',
    note: 'Live on JM FX desk — read-only snapshot in Lab',
    status: 'live-ref',
  },
]
